ALTER TABLE "Combatant" ADD COLUMN "defenseFinal" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Combatant" ADD COLUMN "attackBonus" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Combatant" ADD COLUMN "damageFormula" VARCHAR(50) NOT NULL DEFAULT '1d6';
